foreground            #dee3e6
background            #0f1416
selection_foreground  #cfe6f1
selection_background  #344a52
url_color             #88d1ec

# black
color0   #40484c
color8   #8a9296

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #88d1ec
color10  #004d61

# yellow
color3   #c3c3eb
color11  #434465

# blue
color4   #b3cad4
color12  #344a52

# magenta
color5   #08677f
color13  #004d61

# cyan
color6   #40484c
color14  #bfc8cc

# white
color7   #dee3e6
color15  #bfc8cc
