foreground            #dde4e4
background            #0e1415
selection_foreground  #cce8e9
selection_background  #324b4d
url_color             #80d4da

# black
color0   #3f4949
color8   #899393

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #80d4da
color10  #004f53

# yellow
color3   #b6c7ea
color11  #374764

# blue
color4   #b1cccd
color12  #324b4d

# magenta
color5   #00696e
color13  #004f53

# cyan
color6   #3f4949
color14  #bec8c9

# white
color7   #dde4e4
color15  #bec8c9
